"""cria_modulo_direcao_comercial_mvp

Revision ID: 2295ed8b2647
Revises: ecf447a82788
Create Date: 2026-10-04 13:38:58.494505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2295ed8b2647'
down_revision: Union[str, None] = 'ecf447a82788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agencia_id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('meta_faturacao', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('meta_contactos', sa.Integer(), nullable=False),
    sa.Column('meta_reunioes', sa.Integer(), nullable=False),
    sa.Column('meta_angariacoes', sa.Integer(), nullable=False),
    sa.Column('meta_exclusivos', sa.Integer(), nullable=False),
    sa.Column('meta_visitas', sa.Integer(), nullable=False),
    sa.Column('meta_propostas', sa.Integer(), nullable=False),
    sa.Column('meta_cpcv', sa.Integer(), nullable=False),
    sa.Column('meta_escrituras', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='chk_goal_mes'),
    sa.ForeignKeyConstraint(['agencia_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consultor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agencia_id', 'consultor_id', 'ano', 'mes', name='uq_goals_agencia_consultor_ano_mes')
    )
    op.create_index(op.f('ix_goals_agencia_id'), 'goals', ['agencia_id'], unique=False)
    op.create_index(op.f('ix_goals_ano'), 'goals', ['ano'], unique=False)
    op.create_index(op.f('ix_goals_consultor_id'), 'goals', ['consultor_id'], unique=False)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_mes'), 'goals', ['mes'], unique=False)
    op.create_table('weekly_meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agencia_id', sa.Integer(), nullable=False),
    sa.Column('diretor_id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('data_reuniao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('semana_ano', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('contactos_realizados', sa.Integer(), nullable=False),
    sa.Column('reunioes_realizadas', sa.Integer(), nullable=False),
    sa.Column('angariacoes_realizadas', sa.Integer(), nullable=False),
    sa.Column('visitas_realizadas', sa.Integer(), nullable=False),
    sa.Column('propostas_realizadas', sa.Integer(), nullable=False),
    sa.Column('cpcv_realizados', sa.Integer(), nullable=False),
    sa.Column('faturacao_realizada', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dificuldade_principal', sa.Text(), nullable=True),
    sa.Column('negocio_prioritario', sa.Text(), nullable=True),
    sa.Column('diagnostico_diretor', sa.Text(), nullable=True),
    sa.Column('estrategia_definida', sa.Text(), nullable=True),
    sa.Column('apoio_direcao_necessario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agencia_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consultor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diretor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_meetings_agencia_id'), 'weekly_meetings', ['agencia_id'], unique=False)
    op.create_index(op.f('ix_weekly_meetings_ano'), 'weekly_meetings', ['ano'], unique=False)
    op.create_index(op.f('ix_weekly_meetings_consultor_id'), 'weekly_meetings', ['consultor_id'], unique=False)
    op.create_index(op.f('ix_weekly_meetings_data_reuniao'), 'weekly_meetings', ['data_reuniao'], unique=False)
    op.create_index(op.f('ix_weekly_meetings_diretor_id'), 'weekly_meetings', ['diretor_id'], unique=False)
    op.create_index(op.f('ix_weekly_meetings_id'), 'weekly_meetings', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_meetings_semana_ano'), 'weekly_meetings', ['semana_ano'], unique=False)
    op.create_table('meeting_commitments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('descricao_compromisso', sa.String(length=255), nullable=False),
    sa.Column('meta_quantitativa', sa.String(length=100), nullable=True),
    sa.Column('prazo_data', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('percentual_cumprimento', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('Pendente', 'Cumprido', 'Parcial', 'NaoCumprido')", name='chk_commitment_status'),
    sa.CheckConstraint('percentual_cumprimento >= 0 AND percentual_cumprimento <= 100', name='chk_commitment_percentual'),
    sa.ForeignKeyConstraint(['consultor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['weekly_meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_commitments_consultor_id'), 'meeting_commitments', ['consultor_id'], unique=False)
    op.create_index(op.f('ix_meeting_commitments_id'), 'meeting_commitments', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_commitments_meeting_id'), 'meeting_commitments', ['meeting_id'], unique=False)
    op.create_table('pipeline_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agencia_id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('cliente_nome', sa.String(length=255), nullable=False),
    sa.Column('cliente_telefone', sa.String(length=50), nullable=False),
    sa.Column('tipo_negocio', sa.String(length=50), nullable=False),
    sa.Column('valor_imovel', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comissao_estimada', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fase', sa.String(length=50), nullable=False),
    sa.Column('probabilidade', sa.Integer(), nullable=False),
    sa.Column('data_prevista_fecho', sa.Date(), nullable=True),
    sa.Column('proxima_acao', sa.String(length=255), nullable=True),
    sa.Column('data_proxima_acao', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("fase IN ('Lead', 'Qualificacao', 'Angariacao', 'Visita', 'Proposta', 'Negociacao', 'CPCV', 'Escritura', 'Ganho', 'Perdido')", name='chk_deal_fase'),
    sa.CheckConstraint("tipo_negocio IN ('Venda', 'Angariação', 'Compra')", name='chk_deal_tipo_negocio'),
    sa.CheckConstraint('probabilidade >= 0 AND probabilidade <= 100', name='chk_deal_probabilidade'),
    sa.ForeignKeyConstraint(['agencia_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consultor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_deals_agencia_id'), 'pipeline_deals', ['agencia_id'], unique=False)
    op.create_index(op.f('ix_pipeline_deals_ativo'), 'pipeline_deals', ['ativo'], unique=False)
    op.create_index(op.f('ix_pipeline_deals_consultor_id'), 'pipeline_deals', ['consultor_id'], unique=False)
    op.create_index(op.f('ix_pipeline_deals_fase'), 'pipeline_deals', ['fase'], unique=False)
    op.create_index(op.f('ix_pipeline_deals_id'), 'pipeline_deals', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_deals_property_id'), 'pipeline_deals', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_deals_property_id'), table_name='pipeline_deals')
    op.drop_index(op.f('ix_pipeline_deals_id'), table_name='pipeline_deals')
    op.drop_index(op.f('ix_pipeline_deals_fase'), table_name='pipeline_deals')
    op.drop_index(op.f('ix_pipeline_deals_consultor_id'), table_name='pipeline_deals')
    op.drop_index(op.f('ix_pipeline_deals_ativo'), table_name='pipeline_deals')
    op.drop_index(op.f('ix_pipeline_deals_agencia_id'), table_name='pipeline_deals')
    op.drop_table('pipeline_deals')
    op.drop_index(op.f('ix_meeting_commitments_meeting_id'), table_name='meeting_commitments')
    op.drop_index(op.f('ix_meeting_commitments_id'), table_name='meeting_commitments')
    op.drop_index(op.f('ix_meeting_commitments_consultor_id'), table_name='meeting_commitments')
    op.drop_table('meeting_commitments')
    op.drop_index(op.f('ix_weekly_meetings_semana_ano'), table_name='weekly_meetings')
    op.drop_index(op.f('ix_weekly_meetings_id'), table_name='weekly_meetings')
    op.drop_index(op.f('ix_weekly_meetings_diretor_id'), table_name='weekly_meetings')
    op.drop_index(op.f('ix_weekly_meetings_data_reuniao'), table_name='weekly_meetings')
    op.drop_index(op.f('ix_weekly_meetings_consultor_id'), table_name='weekly_meetings')
    op.drop_index(op.f('ix_weekly_meetings_ano'), table_name='weekly_meetings')
    op.drop_index(op.f('ix_weekly_meetings_agencia_id'), table_name='weekly_meetings')
    op.drop_table('weekly_meetings')
    op.drop_index(op.f('ix_goals_mes'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_consultor_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_ano'), table_name='goals')
    op.drop_index(op.f('ix_goals_agencia_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
