"""cria_modulo_leads_angariacao

Revision ID: ecf447a82788
Revises: 0001_initial_schema
Create Date: 2026-09-30 00:29:10.225498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf447a82788'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads_blacklist_rgpd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agencia_id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agencia_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agencia_id', 'telefone', name='uq_blacklist_agencia_telefone')
    )
    op.create_index(op.f('ix_leads_blacklist_rgpd_agencia_id'), 'leads_blacklist_rgpd', ['agencia_id'], unique=False)
    op.create_index(op.f('ix_leads_blacklist_rgpd_id'), 'leads_blacklist_rgpd', ['id'], unique=False)
    op.create_index(op.f('ix_leads_blacklist_rgpd_telefone'), 'leads_blacklist_rgpd', ['telefone'], unique=False)
    op.create_table('leads_angariacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agencia_id', sa.Integer(), nullable=False),
    sa.Column('consultor_atribuido_id', sa.Integer(), nullable=True),
    sa.Column('fonte', sa.String(length=50), nullable=False),
    sa.Column('referencia_externa', sa.String(length=100), nullable=False),
    sa.Column('url_origem', sa.Text(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('preco_solicitado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_minimo_abertura', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('concelho', sa.String(length=100), nullable=True),
    sa.Column('freguesia', sa.String(length=100), nullable=True),
    sa.Column('morada_aproximada', sa.String(length=255), nullable=True),
    sa.Column('nome_contacto', sa.String(length=255), nullable=True),
    sa.Column('telefone_contacto', sa.String(length=50), nullable=True),
    sa.Column('tipo_anunciante', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('imovel_convertido_id', sa.Integer(), nullable=True),
    sa.Column('data_limite_leilao', sa.DateTime(), nullable=True),
    sa.Column('notas_prospeccao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('Novo', 'Em Prospeccao', 'Convertido', 'Descartado', 'Oposicao_RGPD')", name='chk_lead_status'),
    sa.ForeignKeyConstraint(['agencia_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consultor_atribuido_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['imovel_convertido_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agencia_id', 'fonte', 'referencia_externa', name='uq_lead_agencia_fonte_ref')
    )
    op.create_index(op.f('ix_leads_angariacao_agencia_id'), 'leads_angariacao', ['agencia_id'], unique=False)
    op.create_index(op.f('ix_leads_angariacao_concelho'), 'leads_angariacao', ['concelho'], unique=False)
    op.create_index(op.f('ix_leads_angariacao_consultor_atribuido_id'), 'leads_angariacao', ['consultor_atribuido_id'], unique=False)
    op.create_index(op.f('ix_leads_angariacao_fonte'), 'leads_angariacao', ['fonte'], unique=False)
    op.create_index(op.f('ix_leads_angariacao_id'), 'leads_angariacao', ['id'], unique=False)
    op.create_index(op.f('ix_leads_angariacao_imovel_convertido_id'), 'leads_angariacao', ['imovel_convertido_id'], unique=False)
    op.create_index(op.f('ix_leads_angariacao_preco_solicitado'), 'leads_angariacao', ['preco_solicitado'], unique=False)
    op.create_index(op.f('ix_leads_angariacao_referencia_externa'), 'leads_angariacao', ['referencia_externa'], unique=False)
    op.create_index(op.f('ix_leads_angariacao_status'), 'leads_angariacao', ['status'], unique=False)
    op.create_index(op.f('ix_leads_angariacao_telefone_contacto'), 'leads_angariacao', ['telefone_contacto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_angariacao_telefone_contacto'), table_name='leads_angariacao')
    op.drop_index(op.f('ix_leads_angariacao_status'), table_name='leads_angariacao')
    op.drop_index(op.f('ix_leads_angariacao_referencia_externa'), table_name='leads_angariacao')
    op.drop_index(op.f('ix_leads_angariacao_preco_solicitado'), table_name='leads_angariacao')
    op.drop_index(op.f('ix_leads_angariacao_imovel_convertido_id'), table_name='leads_angariacao')
    op.drop_index(op.f('ix_leads_angariacao_id'), table_name='leads_angariacao')
    op.drop_index(op.f('ix_leads_angariacao_fonte'), table_name='leads_angariacao')
    op.drop_index(op.f('ix_leads_angariacao_consultor_atribuido_id'), table_name='leads_angariacao')
    op.drop_index(op.f('ix_leads_angariacao_concelho'), table_name='leads_angariacao')
    op.drop_index(op.f('ix_leads_angariacao_agencia_id'), table_name='leads_angariacao')
    op.drop_table('leads_angariacao')
    op.drop_index(op.f('ix_leads_blacklist_rgpd_telefone'), table_name='leads_blacklist_rgpd')
    op.drop_index(op.f('ix_leads_blacklist_rgpd_id'), table_name='leads_blacklist_rgpd')
    op.drop_index(op.f('ix_leads_blacklist_rgpd_agencia_id'), table_name='leads_blacklist_rgpd')
    op.drop_table('leads_blacklist_rgpd')
    # ### end Alembic commands ###
